
superlig360:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: password
      port: 5432
      dbname: superlig360
      schema: analytics_superlig
      threads: 1
