
version: 2

models:
  - name: stg_players
    columns:
      - name: player_id
        tests:
          - unique
          - not_null

  - name: stg_matches
    columns:
      - name: match_id
        tests:
          - unique
          - not_null
      - name: home_score
        tests:
          - not_null
    tests:
      - dbt_utils.expression_is_true:
          expression: "home_score >= 0"
      - dbt_utils.expression_is_true:
          expression: "away_score >= 0"
